title: Cameron King
description: Cameron King portfolio
author: aliking
email: ""
baseurl: ""
url: "https://cameron.kiii.ing"

# Build settings
theme: null
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

kramdown:
  input: GFM

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll_picture_tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - README.md

# custom
project_asset:
  asset_root: assets/project_media

stack_styles:
  tape1: locked #F00 #F00 #F00 #0F0 #0F0 #0F0
